print('Hi "python", how are you?')
print("Hi 'python', how are you?")
#print("Hi "python", how are you?")
#print('Hi 'python', how are you?')
print('''Hi 'python', how are you?''')
print('''Hi "python", how are you?''')
print("""Hi 'python', how are you?""")
print("""Hi "python", how are you?""")
